CC = g++-11 -g -Wall -fdiagnostics-color=always

TrieTest: TrieTest.o Trie.o
	$(CC) -o TrieTest TrieTest.cpp

TrieTest.o: TrieTest.cpp
	$(CC) -c TrieTest.cpp

Trie.o: Trie.cpp
	$(CC) -c Trie.cpp

clean:
	echo 'not implemented'

test:
	echo 'not implemented'
